/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainExamen;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casti
 */
public class MainExamen extends javax.swing.JFrame {

    private ArrayList<Libros> listaLibros = new ArrayList();
    private ArrayList<Libros> listBuy = new ArrayList();
    private double saldoUser = 9999;

    /**
     * Creates new form MainExamen
     */
    public MainExamen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPantallaAdmin = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        userLabel5 = new javax.swing.JLabel();
        Jtxtf_TituloCrear = new javax.swing.JTextField();
        userLabel6 = new javax.swing.JLabel();
        Jtxtf_AutorCrear = new javax.swing.JTextField();
        userLabel7 = new javax.swing.JLabel();
        jff_PrecioCrear = new javax.swing.JFormattedTextField();
        tbn_CerrarSesionPublicar = new javax.swing.JButton();
        btn_PublicarNoFicc = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        userLabel8 = new javax.swing.JLabel();
        jff_CursoCrear = new javax.swing.JFormattedTextField();
        Jtxtf_FacultadCrear = new javax.swing.JTextField();
        userLabel9 = new javax.swing.JLabel();
        btn_PublicarText = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        userLabel10 = new javax.swing.JLabel();
        jcb_TipoRef = new javax.swing.JComboBox<>();
        btn_PublicarRef = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        userLabel11 = new javax.swing.JLabel();
        jcb_TipoFicc = new javax.swing.JComboBox<>();
        btn_PublicarFicc = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        userLabel12 = new javax.swing.JLabel();
        jcb_TipoNoFicc = new javax.swing.JComboBox<>();
        btn_PublicarFiccNo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jcb_TipoListar = new javax.swing.JComboBox<>();
        userLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_ListTipos = new javax.swing.JTextArea();
        tbn_CerrarSesionListar = new javax.swing.JButton();
        ListarLib = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        userLabel14 = new javax.swing.JLabel();
        jcb_TipoMod = new javax.swing.JComboBox<>();
        jcb_Mod = new javax.swing.JComboBox<>();
        userLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_ListLibroMod = new javax.swing.JTextArea();
        userLabel16 = new javax.swing.JLabel();
        Jtxtf_TituloMod = new javax.swing.JTextField();
        userLabel17 = new javax.swing.JLabel();
        Jtxtf_AutorMod = new javax.swing.JTextField();
        userLabel18 = new javax.swing.JLabel();
        jff_PrecioMod = new javax.swing.JFormattedTextField();
        btn_Edit = new javax.swing.JButton();
        tbn_CerrarSesionEditar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        userLabel19 = new javax.swing.JLabel();
        jcb_TipoDel = new javax.swing.JComboBox<>();
        userLabel20 = new javax.swing.JLabel();
        jcb_LibroDel = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtA_ListDel = new javax.swing.JTextArea();
        btn_Delete = new javax.swing.JButton();
        tbn_CerrarSesionEliminar = new javax.swing.JButton();
        jdPantallaUser = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea_TransComprar = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtArea_Comprar = new javax.swing.JTextArea();
        userLabel21 = new javax.swing.JLabel();
        jcb_TipoComprar = new javax.swing.JComboBox<>();
        userLabel22 = new javax.swing.JLabel();
        jcb_LibroComprar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_Comprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tbn_CerrarSesionComprar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtArea_Devolver = new javax.swing.JTextArea();
        userLabel23 = new javax.swing.JLabel();
        jcb_TipoDev = new javax.swing.JComboBox<>();
        userLabel24 = new javax.swing.JLabel();
        jcb_LibroDev = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtArea_TransDev = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_Devolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tbn_CerrarSesionDevolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        userLabel3 = new javax.swing.JLabel();
        userLabel4 = new javax.swing.JLabel();
        Jtxtf_ContraAdmin = new javax.swing.JTextField();
        Jtxtf_UserAdmin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_LogUser = new javax.swing.JButton();
        btn_LogAdmin = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        userLabel5.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel5.setForeground(new java.awt.Color(51, 51, 51));
        userLabel5.setText("Titulo:");

        Jtxtf_TituloCrear.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_TituloCrear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_TituloCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel6.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel6.setForeground(new java.awt.Color(51, 51, 51));
        userLabel6.setText("Autor:");

        Jtxtf_AutorCrear.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_AutorCrear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_AutorCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel7.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel7.setForeground(new java.awt.Color(51, 51, 51));
        userLabel7.setText("Precio:");

        jff_PrecioCrear.setBackground(new java.awt.Color(255, 255, 255));
        jff_PrecioCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jff_PrecioCrear.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        tbn_CerrarSesionPublicar.setText("Cerrar Sesion");
        tbn_CerrarSesionPublicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_CerrarSesionPublicarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(userLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Jtxtf_TituloCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(userLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jff_PrecioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(userLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Jtxtf_AutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tbn_CerrarSesionPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tbn_CerrarSesionPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel5)
                    .addComponent(Jtxtf_TituloCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel6)
                    .addComponent(Jtxtf_AutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jff_PrecioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel7))
                .addGap(61, 61, 61))
        );

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));

        userLabel8.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel8.setForeground(new java.awt.Color(51, 51, 51));
        userLabel8.setText("Curso:");

        jff_CursoCrear.setBackground(new java.awt.Color(255, 255, 255));
        jff_CursoCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jff_CursoCrear.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        Jtxtf_FacultadCrear.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_FacultadCrear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_FacultadCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel9.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel9.setForeground(new java.awt.Color(51, 51, 51));
        userLabel9.setText("Facultad:");

        btn_PublicarText.setText("Publicar Libro");
        btn_PublicarText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PublicarTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(userLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jtxtf_FacultadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(userLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jff_CursoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(btn_PublicarText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jff_CursoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel8))
                .addGap(60, 60, 60)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel9)
                    .addComponent(Jtxtf_FacultadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_PublicarText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btn_PublicarNoFicc.addTab("Libro de Texto", jPanel13);

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));

        userLabel10.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel10.setForeground(new java.awt.Color(51, 51, 51));
        userLabel10.setText("Tipo:");

        jcb_TipoRef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diccionario", "Enciclopedia", "Manual Tecnico", "Tescuno" }));

        btn_PublicarRef.setText("Publicar Libro");
        btn_PublicarRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PublicarRefMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(userLabel10)
                .addGap(26, 26, 26)
                .addComponent(jcb_TipoRef, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_PublicarRef, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel10)
                    .addComponent(jcb_TipoRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btn_PublicarRef, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        btn_PublicarNoFicc.addTab("Libro de Referencia", jPanel14);

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));

        userLabel11.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel11.setForeground(new java.awt.Color(51, 51, 51));
        userLabel11.setText("Tipo:");

        jcb_TipoFicc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novela", "Sci-fi", "Misterio", "Aventura" }));

        btn_PublicarFicc.setText("Publicar Libro");
        btn_PublicarFicc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PublicarFiccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(userLabel11)
                .addGap(26, 26, 26)
                .addComponent(jcb_TipoFicc, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_PublicarFicc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel11)
                    .addComponent(jcb_TipoFicc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btn_PublicarFicc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        btn_PublicarNoFicc.addTab("Libro de Ficcion", jPanel15);

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));

        userLabel12.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel12.setForeground(new java.awt.Color(51, 51, 51));
        userLabel12.setText("Tipo:");

        jcb_TipoNoFicc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensayo", "Biografia", "Autobiografia", "Revista Cientifica" }));

        btn_PublicarFiccNo.setText("Publicar Libro");
        btn_PublicarFiccNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PublicarFiccNoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(userLabel12)
                .addGap(26, 26, 26)
                .addComponent(jcb_TipoNoFicc, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_PublicarFiccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel12)
                    .addComponent(jcb_TipoNoFicc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btn_PublicarFiccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        btn_PublicarNoFicc.addTab("Libro de No Ficcion", jPanel16);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_PublicarNoFicc)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_PublicarNoFicc))
        );

        jTabbedPane1.addTab("Publicar Libro", jPanel4);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jcb_TipoListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Libros de Texto", "Libros de Referencias", "Libros de Ficcion", "Libros de No Ficcion" }));

        userLabel13.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel13.setForeground(new java.awt.Color(51, 51, 51));
        userLabel13.setText("Tipo:");

        txtA_ListTipos.setColumns(20);
        txtA_ListTipos.setRows(5);
        jScrollPane1.setViewportView(txtA_ListTipos);

        tbn_CerrarSesionListar.setText("Cerrar Sesion");
        tbn_CerrarSesionListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_CerrarSesionListarMouseClicked(evt);
            }
        });

        ListarLib.setText("Listar");
        ListarLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarLibMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tbn_CerrarSesionListar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userLabel13)
                        .addGap(31, 31, 31)
                        .addComponent(jcb_TipoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ListarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_TipoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel13)
                    .addComponent(tbn_CerrarSesionListar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Libro", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        userLabel14.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel14.setForeground(new java.awt.Color(51, 51, 51));
        userLabel14.setText("Tipo:");

        userLabel15.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel15.setForeground(new java.awt.Color(51, 51, 51));
        userLabel15.setText("Libro");

        txtA_ListLibroMod.setColumns(20);
        txtA_ListLibroMod.setRows(5);
        jScrollPane2.setViewportView(txtA_ListLibroMod);

        userLabel16.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel16.setForeground(new java.awt.Color(51, 51, 51));
        userLabel16.setText("Titulo:");

        Jtxtf_TituloMod.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_TituloMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_TituloMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel17.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel17.setForeground(new java.awt.Color(51, 51, 51));
        userLabel17.setText("Autor:");

        Jtxtf_AutorMod.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_AutorMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_AutorMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel18.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel18.setForeground(new java.awt.Color(51, 51, 51));
        userLabel18.setText("Precio:");

        jff_PrecioMod.setBackground(new java.awt.Color(255, 255, 255));
        jff_PrecioMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jff_PrecioMod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btn_Edit.setText("Editar Libro");

        tbn_CerrarSesionEditar.setText("Cerrar Sesion");
        tbn_CerrarSesionEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_CerrarSesionEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(userLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcb_TipoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(userLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcb_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(userLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jff_PrecioMod, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(userLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(Jtxtf_AutorMod, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(userLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(Jtxtf_TituloMod, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbn_CerrarSesionEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_TipoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel14)
                    .addComponent(tbn_CerrarSesionEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel15))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabel16)
                            .addComponent(Jtxtf_TituloMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabel17)
                            .addComponent(Jtxtf_AutorMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jff_PrecioMod, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar Libro", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        userLabel19.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel19.setForeground(new java.awt.Color(51, 51, 51));
        userLabel19.setText("Tipo:");

        userLabel20.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel20.setForeground(new java.awt.Color(51, 51, 51));
        userLabel20.setText("Libro");

        txtA_ListDel.setColumns(20);
        txtA_ListDel.setRows(5);
        jScrollPane3.setViewportView(txtA_ListDel);

        btn_Delete.setText("Eliminar Libro");

        tbn_CerrarSesionEliminar.setText("Cerrar Sesion");
        tbn_CerrarSesionEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_CerrarSesionEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(userLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcb_LibroDel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(tbn_CerrarSesionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(userLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcb_TipoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109)
                .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_TipoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_LibroDel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tbn_CerrarSesionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Libro", jPanel8);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        javax.swing.GroupLayout jdPantallaAdminLayout = new javax.swing.GroupLayout(jdPantallaAdmin.getContentPane());
        jdPantallaAdmin.getContentPane().setLayout(jdPantallaAdminLayout);
        jdPantallaAdminLayout.setHorizontalGroup(
            jdPantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdPantallaAdminLayout.setVerticalGroup(
            jdPantallaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        txtArea_TransComprar.setColumns(20);
        txtArea_TransComprar.setRows(5);
        jScrollPane4.setViewportView(txtArea_TransComprar);

        txtArea_Comprar.setColumns(20);
        txtArea_Comprar.setRows(5);
        jScrollPane5.setViewportView(txtArea_Comprar);

        userLabel21.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel21.setForeground(new java.awt.Color(51, 51, 51));
        userLabel21.setText("Tipo:");

        jcb_TipoComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        userLabel22.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel22.setForeground(new java.awt.Color(51, 51, 51));
        userLabel22.setText("Libro");

        jcb_LibroComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Saldo del Usuario:");

        btn_Comprar.setText("Comprar Libro");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Transacción");

        tbn_CerrarSesionComprar.setText("Cerrar Sesion");
        tbn_CerrarSesionComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_CerrarSesionComprarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(userLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_TipoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(userLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_LibroComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tbn_CerrarSesionComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tbn_CerrarSesionComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_TipoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_LibroComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel22))
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane2.addTab("Comprar Libro", jPanel10);

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        txtArea_Devolver.setColumns(20);
        txtArea_Devolver.setRows(5);
        jScrollPane6.setViewportView(txtArea_Devolver);

        userLabel23.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel23.setForeground(new java.awt.Color(51, 51, 51));
        userLabel23.setText("Tipo:");

        jcb_TipoDev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        userLabel24.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        userLabel24.setForeground(new java.awt.Color(51, 51, 51));
        userLabel24.setText("Libro");

        jcb_LibroDev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtArea_TransDev.setColumns(20);
        txtArea_TransDev.setRows(5);
        jScrollPane7.setViewportView(txtArea_TransDev);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Transacción");

        btn_Devolver.setText("Devolver Libro");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Saldo del Usuario:");

        tbn_CerrarSesionDevolver.setText("Cerrar Sesion");
        tbn_CerrarSesionDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbn_CerrarSesionDevolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(userLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_TipoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(userLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_LibroDev, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbn_CerrarSesionDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(327, 327, 327)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tbn_CerrarSesionDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_TipoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_LibroDev, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_Devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(487, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        jTabbedPane2.addTab("Devolver Libro", jPanel11);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout jdPantallaUserLayout = new javax.swing.GroupLayout(jdPantallaUser.getContentPane());
        jdPantallaUser.getContentPane().setLayout(jdPantallaUserLayout);
        jdPantallaUserLayout.setHorizontalGroup(
            jdPantallaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdPantallaUserLayout.setVerticalGroup(
            jdPantallaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Administrador Log In");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        userLabel3.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel3.setForeground(new java.awt.Color(51, 51, 51));
        userLabel3.setText("Password:");
        jPanel1.add(userLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, 30));

        userLabel4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userLabel4.setForeground(new java.awt.Color(51, 51, 51));
        userLabel4.setText("User Administrador:");
        jPanel1.add(userLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));

        Jtxtf_ContraAdmin.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_ContraAdmin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_ContraAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Jtxtf_ContraAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 280, 30));

        Jtxtf_UserAdmin.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_UserAdmin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Jtxtf_UserAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Jtxtf_UserAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 280, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btn_LogUser.setText("Entrar como Usuario");
        btn_LogUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogUserMouseClicked(evt);
            }
        });

        btn_LogAdmin.setText("Log In Administrador");
        btn_LogAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(659, Short.MAX_VALUE)
                .addComponent(btn_LogUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(469, Short.MAX_VALUE)
                    .addComponent(btn_LogAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(181, 181, 181)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(498, Short.MAX_VALUE)
                .addComponent(btn_LogUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(387, Short.MAX_VALUE)
                    .addComponent(btn_LogAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(141, 141, 141)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogAdminMouseClicked

        if (Jtxtf_UserAdmin.getText().equals("lib123") && Jtxtf_ContraAdmin.getText().equals("321lib")) {

            this.setVisible(false);
            jdPantallaAdmin.pack();
            jdPantallaAdmin.setLocationRelativeTo(null);
            jdPantallaAdmin.setVisible(true);
            //llenarcbTipoList();

        } else {

            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña equivocados.");

        }

    }//GEN-LAST:event_btn_LogAdminMouseClicked

    private void btn_LogUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogUserMouseClicked
        this.setVisible(false);
        jdPantallaUser.pack();
        jdPantallaUser.setLocationRelativeTo(null);
        jdPantallaUser.setVisible(true);
    }//GEN-LAST:event_btn_LogUserMouseClicked

    private void tbn_CerrarSesionPublicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_CerrarSesionPublicarMouseClicked
        jdPantallaAdmin.pack();
        jdPantallaAdmin.setLocationRelativeTo(null);
        jdPantallaAdmin.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_tbn_CerrarSesionPublicarMouseClicked

    private void tbn_CerrarSesionListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_CerrarSesionListarMouseClicked
        jdPantallaAdmin.pack();
        jdPantallaAdmin.setLocationRelativeTo(null);
        jdPantallaAdmin.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_tbn_CerrarSesionListarMouseClicked

    private void tbn_CerrarSesionEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_CerrarSesionEditarMouseClicked
        jdPantallaAdmin.pack();
        jdPantallaAdmin.setLocationRelativeTo(null);
        jdPantallaAdmin.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_tbn_CerrarSesionEditarMouseClicked

    private void tbn_CerrarSesionEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_CerrarSesionEliminarMouseClicked
        jdPantallaAdmin.pack();
        jdPantallaAdmin.setLocationRelativeTo(null);
        jdPantallaAdmin.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_tbn_CerrarSesionEliminarMouseClicked

    private void tbn_CerrarSesionComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_CerrarSesionComprarMouseClicked
        jdPantallaUser.pack();
        jdPantallaUser.setLocationRelativeTo(null);
        jdPantallaUser.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_tbn_CerrarSesionComprarMouseClicked

    private void tbn_CerrarSesionDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbn_CerrarSesionDevolverMouseClicked
        jdPantallaUser.pack();
        jdPantallaUser.setLocationRelativeTo(null);
        jdPantallaUser.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_tbn_CerrarSesionDevolverMouseClicked

    private void btn_PublicarFiccNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PublicarFiccNoMouseClicked

        String titulo = Jtxtf_TituloCrear.getText();
        String autor = Jtxtf_AutorCrear.getText();
        double precio = Double.parseDouble(jff_PrecioCrear.getText());
        Object tipo = jcb_TipoRef.getSelectedItem();

        NoFiccion lib = new NoFiccion((String) tipo, titulo, autor, precio, 1);
        listaLibros.add(lib);

        Jtxtf_TituloCrear.setText("");
        Jtxtf_AutorCrear.setText("");
        jff_PrecioCrear.setText("");
        JOptionPane.showMessageDialog(this, "Libro publicado exitosamente.");

    }//GEN-LAST:event_btn_PublicarFiccNoMouseClicked

    private void btn_PublicarTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PublicarTextMouseClicked
        String titulo = Jtxtf_TituloCrear.getText();
        String autor = Jtxtf_AutorCrear.getText();
        double precio = Double.parseDouble(jff_PrecioCrear.getText());
        int curso = Integer.parseInt(jff_CursoCrear.getText());
        String facu = Jtxtf_FacultadCrear.getText();

        Texto lib = new Texto(curso, facu, titulo, autor, precio, 1);
        listaLibros.add(lib);

        Jtxtf_TituloCrear.setText("");
        Jtxtf_AutorCrear.setText("");
        jff_PrecioCrear.setText("");
        jff_CursoCrear.setText("");
        Jtxtf_FacultadCrear.setText("");
        JOptionPane.showMessageDialog(this, "Libro publicado exitosamente.");
    }//GEN-LAST:event_btn_PublicarTextMouseClicked

    private void btn_PublicarRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PublicarRefMouseClicked

        String titulo = Jtxtf_TituloCrear.getText();
        String autor = Jtxtf_AutorCrear.getText();
        double precio = Double.parseDouble(jff_PrecioCrear.getText());
        Object tipo = jcb_TipoRef.getSelectedItem();

        Referencia lib = new Referencia((String) tipo, titulo, autor, precio, 1);
        listaLibros.add(lib);
        System.out.println(lib.getTipo());
        Jtxtf_TituloCrear.setText("");
        Jtxtf_AutorCrear.setText("");
        jff_PrecioCrear.setText("");
        JOptionPane.showMessageDialog(this, "Libro publicado exitosamente.");

    }//GEN-LAST:event_btn_PublicarRefMouseClicked

    private void btn_PublicarFiccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PublicarFiccMouseClicked

        String titulo = Jtxtf_TituloCrear.getText();
        String autor = Jtxtf_AutorCrear.getText();
        double precio = Double.parseDouble(jff_PrecioCrear.getText());
        Object tipo = jcb_TipoRef.getSelectedItem();

        Ficcion lib = new Ficcion((String) tipo, titulo, autor, precio, 1);
        listaLibros.add(lib);

        Jtxtf_TituloCrear.setText("");
        Jtxtf_AutorCrear.setText("");
        jff_PrecioCrear.setText("");
        JOptionPane.showMessageDialog(this, "Libro publicado exitosamente.");

    }//GEN-LAST:event_btn_PublicarFiccMouseClicked

    private void ListarLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarLibMouseClicked
        ListarTipo();
    }//GEN-LAST:event_ListarLibMouseClicked

    private void ListarTipo() {
        txtA_ListTipos.setText("");
        if (jcb_TipoListar.getSelectedItem().equals("Todos")) {
            String x = "";
            for (Libros lib : listaLibros) {
                x += lib.toString();
                x += "\n\t";
            }
            txtA_ListTipos.setText(x);
        } else if (jcb_TipoListar.getSelectedItem().equals("Libros de Texto")) {

            String x = "";
            for (Libros lib : listaLibros) {
                if (lib instanceof Texto) {
                    x += lib.toString();
                    x += "\n\t";
                }
            }
            txtA_ListTipos.setText(x);

        } else if (jcb_TipoListar.getSelectedItem().equals("Libros de Referencias")) {
            String x = "";
            for (Libros lib : listaLibros) {
                if (lib instanceof Referencia) {
                    x += lib.toString();
                    x += "\n\t";
                }
            }
            txtA_ListTipos.setText(x);

        } else if (jcb_TipoListar.getSelectedItem().equals("Libros de Ficcion")) {
            String x = "";
            for (Libros lib : listaLibros) {
                if (lib instanceof Ficcion) {
                    x += lib.toString();
                    x += "\n\t";
                }
            }
            txtA_ListTipos.setText(x);

        } else if (jcb_TipoListar.getSelectedItem().equals("Libros de No Ficcion")) {
            String x = "";
            for (Libros lib : listaLibros) {
                if (lib instanceof NoFiccion) {
                    x += lib.toString();
                    x += "\n\t";
                }
            }
            txtA_ListTipos.setText(x);

        }

    }

//    private void llenarcbTipoList() {
//        jcb_TipoRef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
//        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_TipoRef.getModel();
//        modelo.removeAllElements();
//        modelo.addElement("Diccionario");
//        modelo.addElement("Enciclopedia");
//        modelo.addElement("Manual Tecnico");
//        modelo.addElement("Tescuno");
//        jcb_TipoRef.setModel(modelo);
//
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtxtf_AutorCrear;
    private javax.swing.JTextField Jtxtf_AutorMod;
    private javax.swing.JTextField Jtxtf_ContraAdmin;
    private javax.swing.JTextField Jtxtf_FacultadCrear;
    private javax.swing.JTextField Jtxtf_TituloCrear;
    private javax.swing.JTextField Jtxtf_TituloMod;
    private javax.swing.JTextField Jtxtf_UserAdmin;
    private javax.swing.JButton ListarLib;
    private javax.swing.JButton btn_Comprar;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Devolver;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_LogAdmin;
    private javax.swing.JButton btn_LogUser;
    private javax.swing.JButton btn_PublicarFicc;
    private javax.swing.JButton btn_PublicarFiccNo;
    private javax.swing.JTabbedPane btn_PublicarNoFicc;
    private javax.swing.JButton btn_PublicarRef;
    private javax.swing.JButton btn_PublicarText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> jcb_LibroComprar;
    private javax.swing.JComboBox<String> jcb_LibroDel;
    private javax.swing.JComboBox<String> jcb_LibroDev;
    private javax.swing.JComboBox<String> jcb_Mod;
    private javax.swing.JComboBox<String> jcb_TipoComprar;
    private javax.swing.JComboBox<String> jcb_TipoDel;
    private javax.swing.JComboBox<String> jcb_TipoDev;
    private javax.swing.JComboBox<String> jcb_TipoFicc;
    private javax.swing.JComboBox<String> jcb_TipoListar;
    private javax.swing.JComboBox<String> jcb_TipoMod;
    private javax.swing.JComboBox<String> jcb_TipoNoFicc;
    private javax.swing.JComboBox<String> jcb_TipoRef;
    private javax.swing.JDialog jdPantallaAdmin;
    private javax.swing.JDialog jdPantallaUser;
    private javax.swing.JFormattedTextField jff_CursoCrear;
    private javax.swing.JFormattedTextField jff_PrecioCrear;
    private javax.swing.JFormattedTextField jff_PrecioMod;
    private javax.swing.JButton tbn_CerrarSesionComprar;
    private javax.swing.JButton tbn_CerrarSesionDevolver;
    private javax.swing.JButton tbn_CerrarSesionEditar;
    private javax.swing.JButton tbn_CerrarSesionEliminar;
    private javax.swing.JButton tbn_CerrarSesionListar;
    private javax.swing.JButton tbn_CerrarSesionPublicar;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea txtA_ListDel;
    private javax.swing.JTextArea txtA_ListLibroMod;
    private javax.swing.JTextArea txtA_ListTipos;
    private javax.swing.JTextArea txtArea_Comprar;
    private javax.swing.JTextArea txtArea_Devolver;
    private javax.swing.JTextArea txtArea_TransComprar;
    private javax.swing.JTextArea txtArea_TransDev;
    private javax.swing.JLabel userLabel10;
    private javax.swing.JLabel userLabel11;
    private javax.swing.JLabel userLabel12;
    private javax.swing.JLabel userLabel13;
    private javax.swing.JLabel userLabel14;
    private javax.swing.JLabel userLabel15;
    private javax.swing.JLabel userLabel16;
    private javax.swing.JLabel userLabel17;
    private javax.swing.JLabel userLabel18;
    private javax.swing.JLabel userLabel19;
    private javax.swing.JLabel userLabel20;
    private javax.swing.JLabel userLabel21;
    private javax.swing.JLabel userLabel22;
    private javax.swing.JLabel userLabel23;
    private javax.swing.JLabel userLabel24;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JLabel userLabel5;
    private javax.swing.JLabel userLabel6;
    private javax.swing.JLabel userLabel7;
    private javax.swing.JLabel userLabel8;
    private javax.swing.JLabel userLabel9;
    // End of variables declaration//GEN-END:variables
}
